// export interface User {
//   user_id: number;
//   full_name: string;
//   email: string;
//   phone_number: string | null;
//   role_id: number;
//   last_login: string | null;
// }

export interface Faculty {
  faculty_id: number;
  faculty_name: string;
  created_at?: string;
  updated_at?: string;
}

export interface Major {
  major_id: number;
  major_name: string;
  faculty_id: number;
  created_at?: string;
  updated_at?: string;

  faculty?: Faculty;
}

export interface NavItem {
    id?: string;        // ID untuk navigasi/route identification
    label: string;      // Label yang muncul di sidebar
    icon: string;       // Nama icon Material Symbols
    active?: boolean;   // Status aktif
    children?: NavItem[]; // Untuk submenu (nested)
}

export interface Room {
  room_id: number;
  room_name: string;
  building: string;
  floor: string; // Tambahkan ini
  capacity: number;
}

export interface Course {
  course_id: number;
  course_code: string;
  course_name: string;
  sks: number;
  description?: string;

  // Foreign Keys
  faculty_id: number;
  major_id: number;

  // Relationships
  faculty?: Faculty;
  major?: Major;
}

export interface Semester {
  semester_id: number;
  semester_name: string; // "Ganjil 2024/2025" (Generated by Backend)
  academic_year: string; // "2024/2025"
  term: 'Ganjil' | 'Genap' | 'Pendek'; // Sesuaikan Enum Anda
  start_date: string;
  end_date: string;
  is_active: boolean; // 0 or 1
}

export interface StudentProfile {
    student_number: string;
    faculty_id: number;
    major_id: number;
    semester_id: number;
    batch_year: number;
    major?: Major;
}

export interface LecturerProfile {
    lecturer_number: string;
    faculty_id: number;
    title: string;
    position: string;
    faculty?: Faculty;
}

export interface User {
    user_id: number;
    full_name: string;
    email: string;
    role_id: number;
    phone_number: string | null;
    birth_date: string | null;
    profile_picture: string | null;
    student_profile?: StudentProfile; // Relasi optional
    lecturer_profile?: LecturerProfile; // Relasi optional
}

// resources/js/types.ts

// ... (Interface lain biarkan) ...

export interface CourseClass {
  class_id: number;
  // Karena kita tidak menyimpan 'name' manual (misal "Kelas A"),
  // kita bisa generate atau ambil dari backend jika ada kolom 'class_name'
  class_name?: string;

  course_id: number;
  semester_id: number;
  room_id: number;
  lecturer_id: number; // ID User dosen

  day: string; // 'Monday', 'Tuesday'...
  start_time: string; // <-- GANTI DARI time_start
  end_time: string;   // <-- GANTI DARI time_end

  // Relationships
  course?: Course;
  semester?: Semester;
  room?: Room;
  lecturer?: User; // Lecturer adalah User
}

export interface Curriculum {
  curriculum_id: number;
  major_id: number;
  course_id: number;
  semester: number; // 1-8
  category: 'MKU' | 'WAJIB_PRODI' | 'WAJIB_FAKULTAS' | 'PILIHAN';
  academic_year: number; // 2024

  // Relationships
  major?: Major;
  course?: Course;
}

export interface CostComponent {
  cost_component_id: number;
  component_name: string;
  component_code: string;
  billing_type: 'PER_SKS' | 'PER_COURSE' | 'PER_SEMESTER' | 'ONE_TIME';
  amount: number; // Nominal biaya
  created_at?: string;
  updated_at?: string;
}

export interface Billing {
  billing_id: number;
  description: string;
  amount: number;
  due_date: string;
  status: 'unpaid' | 'paid' | 'overdue';
  cost_component?: { component_name: string };
  semester?: { semester_name: string };
}

// ... (Kode sebelumnya biarkan saja) ...

// --- KRS Related Types ---

export interface KrsItem {
  krs_item_id: number;
  krs_id: number;
  class_id: number;
  sks: number;
  status: 'pending' | 'approved' | 'rejected' | 'draft';

  // Relationship
  class?: CourseClass;
}

export interface KrsRequest {
  krs_id: number;
  student_id: number;
  semester_id: number;
  status: 'draft' | 'submitted' | 'approved' | 'rejected';
  total_sks: number;

  // Relationship
  items: KrsItem[];
}

// Interface khusus untuk data "Available Classes" yang sudah di-mapping di Controller
export interface AvailableClassItem {
  id: number; // class_id
  courseCode: string;
  courseName: string;
  className: string;
  category: string;
  sks: number;
  lecturer: string;
  day: string;
  start_time: string; // String HH:mm
  end_time: string;   // String HH:mm
  room: string;
  quota: number;
  enrolled: number;
  isFull: boolean;
  isTaken: boolean;
}

// --- Page Props Interfaces ---

export interface StudentKrsPageProps {
  auth: {
      user: User;
  };
  krs: KrsRequest;
  availableClasses: AvailableClassItem[];
  maxSks: number;
  flash: {
      success?: string;
      error?: string;
  };
}

export interface PageProps {
  auth: { user: User };
  flash: { success?: string; error?: string };
  // TAMBAHKAN INI:
  env: {
      midtrans_client_key: string;
  };
}

